name: Gradle CI

on:
  workflow_call:
    inputs:
      java-versions:
        description: "Java versions to test against"
        required: false
        default: '["17", "21", "25"]'
        type: string

jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions:
      security-events: write
      actions: read
      contents: read
    strategy:
      fail-fast: false
      matrix:
        java: ${{ fromJSON(inputs.java-versions) }}
        os: ["ubuntu-latest"]
    name: Java ${{ matrix.java }} (${{ matrix.os }})

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: "0"

      - name: "Setup Git"
        shell: bash
        run: |
          git branch -a
          for branch in $(
            git branch -a \
              | grep '^\s*remotes' \
              | egrep --invert-match '(:?HEAD|remotes/pull/[0-9]+/merge)$' \
              | grep -v "HEAD" \
              | sed -e "s/^.*remotes\/origin\///"
          ); do
              echo setting up $branch
              git checkout $branch
              git checkout -
          done
          git branch -a
          git remote remove origin
          git remote add origin git@github.com:${GITHUB_REPOSITORY}.git
          git remote -v

      - name: Setup java
        uses: actions/setup-java@v5
        with:
          distribution: "zulu"
          java-version: ${{ matrix.java }}
          cache: gradle

      - name: prepare Gradle
        shell: bash
        run: |
          mkdir -p ~/.gradle && echo "org.gradle.daemon=false" >> ~/.gradle/gradle.properties

      - name: Check formatting
        shell: bash
        run: |
          ./gradlew --no-daemon spotlessJavaCheck

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"

      - name: "Gradle build"
        shell: bash
        run: |
          java -version
          javac -version
          ./gradlew --no-daemon build

      - name: Transform static code analysis to SARIF
        if: ${{ (success() || failure()) }}
        run: |
          localdir=$(pwd)
          cd ..
          npx violations-command-line -sarif $localdir/sarif-report.json \
          -v "FINDBUGS" "$localdir" ".*build/reports/spotbugs/main\.xml$" "Spotbugs" \
          -v "CHECKSTYLE" "$localdir" ".*build/reports/checkstyle/main\.xml$" "Checkstyle" \
          -v "PMD" "$localdir" ".*build/reports/pmd/main\.xml$" "PMD" \
          -v "JUNIT" "$localdir" ".*/build/test-results/test/TEST-.*\.xml$" "JUNIT"

      - uses: github/codeql-action/upload-sarif@v4
        if: ${{ (success() || failure()) }}
        with:
          sarif_file: sarif-report.json
          category: violations-lib

      - name: Publish Build
        uses: actions/upload-artifact@v5
        if: failure()
        with:
          name: build-${{ github.run_number }}-${{ matrix.os }}-${{ matrix.java }}
          path: ${{ github.workspace }}
