name: Lint Workflows
on:
  pull_request:
  push:

jobs:
  yamllint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Create fake requirements.txt
        run: echo "yamllint" > requirements.txt

      - name: Set up Python and cache
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Install yamllint
        run: pip install yamllint

      - name: Create yamllint config
        run: |
          cat <<EOF > .yamllint.yml
          extends: default
          rules:
            line-length:
              max: 80
              level: warning
              allow-non-breakable-inline-mappings: true
            indentation:
              spaces: 2
              indent-sequences: true
            trailing-spaces: disable
            document-start:
              present: true
            comments:
              min-spaces-from-content: 2
          EOF

      - name: Lint YAML workflows
        run: |
          echo "Searching for YAML files..."
          files=$(find .github/workflows -type f \( -name "*.yml" -o -name "*.yaml" \))
          if [ -z "$files" ]; then
            echo "No YAML files found."
            exit 0
          fi
          echo "Found files:"
          echo "$files"
          yamllint -c .yamllint.yml $files
